#if !canImport(ObjectiveC)
import XCTest

extension AbortTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AbortTests = [
        ("test_abort", test_abort),
        ("test_forceCast", test_forceCast),
    ]
}

extension XCTAssertCrashTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XCTAssertCrashTests = [
        ("test_assert", test_assert),
        ("test_assertionFailure", test_assertionFailure),
        ("test_fatalError", test_fatalError),
        ("test_forceTry", test_forceTry),
        ("test_forceUnwrap", test_forceUnwrap),
        ("test_forceUnwrapAtKeyPathPostfix", test_forceUnwrapAtKeyPathPostfix),
        ("test_overflow", test_overflow),
        ("test_precondition", test_precondition),
        ("test_preconditionFailure", test_preconditionFailure),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AbortTests.__allTests__AbortTests),
        testCase(XCTAssertCrashTests.__allTests__XCTAssertCrashTests),
    ]
}
#endif
