name: Nightly

on:
  push:
    branches: [master]
  pull_request:
    paths: ['Sources/*', 'Tests/*', 'Package*', '.github/workflows/nightly.yml']
  schedule:
    - cron: '0 4 * * *'

jobs:
  Nightly:
    runs-on: ubuntu-latest
    container:
      image: norionomura/swift:nightly
    steps:
      - uses: actions/checkout@v1
      - run: swift test --parallel
