name: SwiftLint

on:
  pull_request:
    paths:
    - '*.swift'
    - '.swiftlint.yml'
    - '.github/workflows/swiftlint.yml'

jobs:
  SwiftLint:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: GitHub Action for SwiftLint
      uses: norio-nomura/action-swiftlint@2.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
