name: xcodebuild

on:
  push:
    branches: [master]
    paths: 
      - '.github/workflows/xcodebuild.yml'
      - 'XCTAssertCrash.xcodeproj/**'
      - 'Sources/**'
      - 'Tests/**'
      - '!Tests/LinuxMain.swift'
  pull_request:
    paths:
      - '.github/workflows/xcodebuild.yml'
      - 'XCTAssertCrash.xcodeproj/**'
      - 'Sources/**'
      - 'Tests/**'
      - '!Tests/LinuxMain.swift'

jobs:
  xcodebuild:
    strategy:
      matrix:
        developer_dir:
          - '/Applications/Xcode_10.2.app'
          - '/Applications/Xcode_10.2.1.app'
          - '/Applications/Xcode_10.3.app'
          - '/Applications/Xcode_11.app'
        xcode_flags: ['-scheme XCTAssertCrash-Package -project XCTAssertCrash.xcodeproj -enableCodeCoverage YES -parallel-testing-enabled NO test']
    runs-on: macOS-10.14
    steps:
      - uses: actions/checkout@v1
      - run: xcodebuild -version
        env: { 'DEVELOPER_DIR': '${{ matrix.developer_dir }}' }
      - name: macOS
        if: always()
        env: { 'DEVELOPER_DIR': '${{ matrix.developer_dir }}' }
        run: xcodebuild ${{ matrix.xcode_flags }} | xcpretty
        shell: bash
      - name: iPhone Simulator
        if: always()
        env: { 'DEVELOPER_DIR': '${{ matrix.developer_dir }}' }
        run: xcodebuild ${{ matrix.xcode_flags }} -sdk iphonesimulator -destination "name=iPhone 8" | xcpretty
        shell: bash
      - name: Apple TV Simulator
        if: always()
        env: { 'DEVELOPER_DIR': '${{ matrix.developer_dir }}' }
        run: xcodebuild ${{ matrix.xcode_flags }} -sdk appletvsimulator -destination "name=Apple TV 4K" | xcpretty
        shell: bash
      - name: Codecov
        if: contains(matrix.developer_dir, '10.3')
        run: curl -s https://codecov.io/bash | bash -s -- -t ${{ secrets.CODECOV_TOKEN }}
        shell: bash

  Analyze:
    runs-on: macOS-10.14
    steps:
      - uses: actions/checkout@v1
      - name: Generate xcodebuild.log
        if: always()
        env: { 'DEVELOPER_DIR': '/Applications/Xcode_10.3.app' }
        run: xcodebuild -scheme XCTAssertCrash-Package -project XCTAssertCrash.xcodeproj clean build-for-testing > xcodebuild.log
        shell: bash
      - name: Install SwiftLint
        run: HOMEBREW_NO_AUTO_UPDATE=1 brew install https://raw.github.com/Homebrew/homebrew-core/master/Formula/swiftlint.rb
      - name: Run SwiftLint Analyze
        run: swiftlint analyze --strict --compiler-log-path xcodebuild.log
